# 应用配置
spring.application.name=CloudServicePlatform
server.port=8081

# 数据库配置 - 使用MySQL数据库
spring.datasource.url=jdbc:mysql://localhost:3306/cloudservice
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# 数据库初始化配置
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:db/cloudservice.sql
spring.sql.init.encoding=UTF-8
spring.sql.init.continue-on-error=true

# MyBatis配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.cloudserviceplatform.vo
mybatis.configuration.map-underscore-to-camel-case=true
# 全局枚举类型处理器
mybatis.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumTypeHandler

# Thymeleaf配置
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false

# 静态资源配置
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# 日志配置
logging.level.com.example.cloudserviceplatform=INFO
logging.level.org.mybatis=DEBUG
